-- CREATE TABLE "USER"(
--   "ID" BIGINT NOT NULL,
--   "AVATAR" VARCHAR(255),
--   "EMAIL" VARCHAR(255),
--   "LOGIN" VARCHAR(255),
--   "PASSWORD" VARCHAR(255),
--   "USERNAME" VARCHAR(255),
--   "AUTHORITIES" VARCHAR(255)
-- );
-- ALTER TABLE "USER" ADD CONSTRAINT "CONSTRAINT_27" PRIMARY KEY("ID");
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.USER;
-- INSERT INTO "USER" VALUES
-- (1, 'boy-7.png', 'uuu@uuu.pl', 'uuu', '{bcrypt}$2a$10$I0uWuhWjubbkUMRlfi.SA.zis2SKMl5CZmxQ9APT3W2evp7TLLwgq', 'uuu', NULL),
-- (203, 'default.png', 'eee@interia.pl', 'eee', '{bcrypt}$2a$10$9TYp3C5y1nt1uKil8lL53e2jm.MN0HwM8MpiipWErGMF26lBIX73m', 'eee', NULL);

-- INSERT INTO "USER" VALUES
-- (1, 'boy-7.png', '1uuu@uuu.pl', '1uuu', '{bcrypt}$2a$10$I0uWuhWjubbkUMRlfi.SA.zis2SKMl5CZmxQ9APT3W2evp7TLLwgq', '1uuu', NULL),
-- (203, 'default.png', '1eee@interia.pl', '1eee', '{bcrypt}$2a$10$9TYp3C5y1nt1uKil8lL53e2jm.MN0HwM8MpiipWErGMF26lBIX73m', '1eee', NULL);



-- CREATE TABLE "PUBLIC"."PARTICIPANTS"(
--   "USER_ID" BIGINT NOT NULL,
--   "PROJECT_ID" BIGINT NOT NULL
-- );

-- ALTER TABLE "PUBLIC"."PARTICIPANTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("USER_ID", "PROJECT_ID");
-- -- 1 +/- SELECT COUNT(*) FROM PUBLIC.PARTICIPANTS;
-- INSERT INTO "PUBLIC"."PARTICIPANTS" VALUES
-- (203, 169);
-- CREATE TABLE "PUBLIC"."PROJECT"(
--   "ID" BIGINT NOT NULL,
--   "DESCRIPTION" VARCHAR(255),
--   "PROJECT_NAME" VARCHAR(255),
--   "USER_ID" BIGINT
-- );
-- ALTER TABLE "PUBLIC"."PROJECT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_18" PRIMARY KEY("ID");
-- -- 3 +/- SELECT COUNT(*) FROM PUBLIC.PROJECT;
-- INSERT INTO "PUBLIC"."PROJECT" VALUES
-- (169, '44588fg123w222', '44121', 1),
-- (171, '2222333311111 b', '22', 1),
-- (201, 'ii desc', 'ii', 1);
-- CREATE TABLE "PUBLIC"."PROJECT_USERS"(
--   "PROJECT_ID" BIGINT NOT NULL,
--   "USERS_ID" BIGINT NOT NULL
-- );
-- ALTER TABLE "PUBLIC"."PROJECT_USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_B" PRIMARY KEY("PROJECT_ID", "USERS_ID");
-- -- 1 +/- SELECT COUNT(*) FROM PUBLIC.PROJECT_USERS;
-- INSERT INTO "PUBLIC"."PROJECT_USERS" VALUES
-- (169, 203);
-- CREATE TABLE "PUBLIC"."PROJECT_PARTICIPANTS"(
--   "ID" BIGINT NOT NULL,
--   "USER_ID" BIGINT
-- );
-- ALTER TABLE "PUBLIC"."PROJECT_PARTICIPANTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");
-- -- 0 +/- SELECT COUNT(*) FROM PUBLIC.PROJECT_PARTICIPANTS;
-- CREATE TABLE "PUBLIC"."SMALL_TASK"(
--   "ID" BIGINT NOT NULL,
--   "SIZE" INTEGER
-- );
-- ALTER TABLE "PUBLIC"."SMALL_TASK" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_67" PRIMARY KEY("ID");
-- -- 1 +/- SELECT COUNT(*) FROM PUBLIC.SMALL_TASK;
-- INSERT INTO "PUBLIC"."SMALL_TASK" VALUES
-- (170, 12);
-- CREATE TABLE "PUBLIC"."SPRINT"(
--   "ID" BIGINT NOT NULL,
--   "FINISH_DATE" DATE,
--   "PLANED_STORY_POINTS" INTEGER,
--   "START_DATE" DATE
-- );
-- ALTER TABLE "PUBLIC"."SPRINT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9" PRIMARY KEY("ID");
-- -- 1 +/- SELECT COUNT(*) FROM PUBLIC.SPRINT;
-- INSERT INTO "PUBLIC"."SPRINT" VALUES
-- (202, DATE '2019-11-08', 10, DATE '2019-11-01');
-- CREATE TABLE "PUBLIC"."TASK"(
--   "ID" BIGINT NOT NULL,
--   "DESCRIPTION" VARCHAR(2000),
--   "NAME" VARCHAR(255),
--   "PROGRESS" INTEGER,
--   "STORY_POINTS" INTEGER,
--   "WEIGHT" INTEGER,
--   "PROJECT_ID" BIGINT,
--   "SPRINT_ID" BIGINT,
--   "USER_ID" BIGINT
-- );
-- ALTER TABLE "PUBLIC"."TASK" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");
-- -- 1 +/- SELECT COUNT(*) FROM PUBLIC.TASK;
-- INSERT INTO "PUBLIC"."TASK" VALUES
-- (204, 'task desc', 'task q', 1, 2, 2, 169, 202, 203);





